[sequential]
# run `maak run get` to run `go get` then `go mod tidy`
get = ["go get", "go mod tidy"]
build = "go build -o build/maak main.go"
	
[parallel]
# run `maak run test` to run below echos and sleep in parallel
# parallel only allows an array of strings
test = ["echo 'this is a test'", "sleep 3", "echo currently sleeping"]
[watch]
# run `maak run watch-build` to run the the build script
# while watching all files ending with `.go` & `.mod`
build = [".go", ".mod"]
# this will watch all files
test = "*"
